services:
  backend:
      image: nassimelhaji/atelierbackend:v2
      build:
        context: ./backend
      ports:
        - "8787:8787"
      networks: 
        - my-network

  frontend:
      image: nassimelhaji/atelierfrontend:v2
      build:
        context: ./frontend
      ports:
        - "80:80"
      depends_on:
        - backend
      networks:
        - my-network


networks:
  my-network:
    driver: bridge